# ====== EXCHANGE / DATA ======
exchange: binance
market_type: futures
timeframe: 5m
lookback_candles: 1000

# ====== TELEGRAM ======
telegram:
  bot_token: ""           # ← isi
  chat_ids: []            # ← isi, contoh: [927202187]

# ====== API KEYS ======
keys:
  binance:
    api_key: ""           # ← API key FUTURES (testnet/mainnet)
    secret:  ""           # ← secret

# ====== LIVE (UMFutures) ======
live:
  enabled: true
  testnet: true                   # mulai dari testnet
  position_mode: oneway           # oneway | hedge
  margin_type: ISOLATED           # ISOLATED | CROSSED
  working_type: MARK_PRICE        # trigger SL/TP pakai mark price
  send_fills_to_telegram: true
  poll_sleep: 10                  # detik (interval polling)
  heartbeat_minutes: 30           # 0 = nonaktif heartbeat

# ====== FEES (informasi saja; tidak dipakai Binance Connector langsung) ======
fees:
  taker: 0.0005                   # 0.0500% (VIP0)
  maker: 0.0002                   # 0.0200% (VIP0)
  bnb_discount: 0.0               # 0.10 kalau aktif bayar fee pakai BNB
  assume_order: taker             # asumsi eksekusi market/taker

# ====== RISK & LEVELS ======
risk:
  leverage: 3
  risk_per_trade: 0.01            # 1% equity pseudo per trade
  entry_source: close             # open | close (ambil harga entry dari candle)
  max_margin_frac: 0.02           # maks 2% equity pseudo dipakai sebagai margin
  max_notional_usdt: 500          # batas absolut notional (anti -2019/-2027, cocok testnet)

  stop_mode: atr                  # atr | percent
  take_profit_rr: 2.0
  atr_entry_period: 14
  atr_entry_mult: 1.5
  atr_trail_period: 12
  atr_trail_mult: 6.0
  min_sl_pct: 0.02                # paksa SL minimal 2% (unlevered)

  breakeven:
    enabled: true
    r_multiple: 1.0               # geser SL saat +1R
    fee_taker_pct: 0.0005         # samakan dengan taker kamu
    slippage_est_pct: 0.0002      # ~0.02% per sisi
    extra_buffer_pct: 0.0001      # buffer ekstra

# ====== ACCOUNT (pseudo equity utk sizing awal) ======
account:
  equity_usdt: 10000

# ====== BOT (opsional, untuk modul sinyal/paper) ======
bot:
  loop_sleep: 30
  snapshot_on_start: false
  min_tp_pct_send: 0.0
  fetch_batch: 10

# ====== PAPER TRADER (abaikan jika hanya live) ======
paper:
  enabled: false                  # set false agar tidak bentrok
  entry_on: next_open             # next_open | close
  min_tp_pct: 0.01
  fetch_batch: 10
  send_fills_to_telegram: true
  out_dir: paper_reports

# ====== STRATEGI ======
strategies: ["ema_cross"]
params:
  ema_short: 9
  ema_long: 21

  # param lain dipakai kalau ganti strategi (aman disimpan)
  bb_len: 20
  bb_std: 1.8
  bb_trend_ma: 0
  bb_require_cmf: false
  bb_allow_shorts: true
  ichimoku_allow_shorts: true
  cmf_len: 20

strategy_per_symbol: {}
params_overrides: {}

# ====== UNIVERSE ======
universe:
  mode: static
  symbols:
    - "BTC/USDT"
    - "ETH/USDT"
    - "BNB/USDT"
    - "XRP/USDT"
    - "ADA/USDT"
